### ISSUE TITLE
Issue rendering a DateTime FieldType

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/datetime-field_type#1]
The default config for time format is not a | separated value. So it errors. I'm about to submit a pull request for this, but there are two solutions. The one I will provided allows for the config to have one value or two values. The alternative is to just supply a | separated value as the default config for the time format.

**Comment by RyanThompson** [comment]
https://github.com/anomalylabs/datetime-field_type/blob/1.0/master/resources/config/config.php

The default has a pipe?

**Comment by RyanThompson** [comment]
I pry need a fallback though for invalid choices from devs.. Or approach that differently

**Comment by bloveless** [comment]
https://github.com/anomalylabs/datetime-field_type/blob/1.0/master/src/DatetimeFieldType.php#L41

I was looking at this line.

Which is referenced from this line. https://github.com/anomalylabs/datetime-field_type/blob/1.0/master/src/DatetimeFieldType.php#L120

**Comment by bloveless** [comment]
Maybe the problem is that the config.php options are getting overwritten somewhere.

**Comment by bloveless** [comment]
Oh also I'm not providing any config options. Just a plain datetime field type.

```
    /**
     * The module fields.
     *
     * @var array
     */
    protected $fields = [
        'title'        => 'anomaly.field_type.text',
        'sub_title'    => 'anomaly.field_type.text',
        'slug'         => [
            'type'   => 'anomaly.field_type.slug',
            'config' => [
                'type'    => '-',
                'slugify' => 'title'
            ]
        ],
        'content'      => 'anomaly.field_type.wysiwyg',
        'release_date' => 'anomaly.field_type.datetime'
    ];
```

**Comment by bloveless** [comment]
That is my migration.

**Comment by RyanThompson** [comment]
This should be the default values: https://github.com/anomalylabs/datetime-field_type/blob/1.0/master/src/DatetimeFieldType.php#L37

**Comment by RyanThompson** [comment]
Which is in the dropdown as well. Not working?
