### ISSUE TITLE
[Datetime-field_type v3] Can't create or edit forms because the date/time format is invalid

### ISSUE THREAD

**Issue by josbarbosa** [anomalylabs/datetime-field_type#14]
One way to reproduce the bug:
Go to posts module -> populate "Publish Date/Time" field -> save/update form
![error_saving_form](https://cloud.githubusercontent.com/assets/25120167/22401456/8c33f060-e5cb-11e6-952d-dc91c23c4917.png)
### I'm having some JS issues too:
![js issues](https://cloud.githubusercontent.com/assets/25120167/22401457/929884f2-e5cb-11e6-831e-be9d4edb4f57.png)

I not dig into the code longly, so I can't provide more info than this.
Sorry :/.

**Comment by RyanThompson** [comment]
Can you update and try again? This is what I get for new posts:

<img width="997" alt="screen shot 2017-01-29 at 12 13 33 am" src="https://cloud.githubusercontent.com/assets/1099967/22402321/fec0e282-e5b7-11e6-90f4-7c6cf214e9c9.png">

**Comment by josbarbosa** [comment]
I did an update and ran some tests again.

The problem that I was having disappeared, but I am facing a weird behavior for the date format "Example: Monday, 30 January, 2017". Still giving me some JS errors and is very difficult to edit the field.
![edit_field_bug](https://cloud.githubusercontent.com/assets/25120167/22447931/9db8ba90-e74d-11e6-8bfb-d725756c3905.png)
All other date time formats are working fine, inside repeaters as well.

I've a question, why you have this 2 options? "pm/am" and "PM/AM"?

I can't find any other problems :). You were right, it suits much better this way, more simple, less code, less problems.

Thanks.

**Comment by RyanThompson** [comment]
Ya I fixed this issue the other day! 

The am / PM .. eh just cause it's there really I suppose :-P
